lala:
  名前: 真中らぁら
  声優: 茜屋日海夏
  誕生日: 11月20日
  学年: 小学5年生
  チーム: SoLaMi SMILE
  口癖: かしこま！

mirei:
  名前: 南みれぃ
  声優: 芹澤優
  学年: 中学1年生
  チーム: SoLaMi SMILE
  口癖: 計算どおり

sophie:
  名前: 北条そふぃ
  声優: 久保田未夢
  学年: 中学2年生
  チーム: SoLaMi SMILE
  口癖: ぷしゅー

shion:
  名前: 東堂シオン
  声優: 山北早紀
  学年: 中学1年生
  チーム: Dressing Pafé
  口癖: いご

dorothy:
  名前: ドロシー・ウェスト
  声優: 澁谷梓希
  学年: 中学1年生
  チーム: Dressing Pafé
  口癖: テンションマックス

leona:
  名前: レオナ・ウェスト
  声優: 若井友希
  学年: 中学1年生
  チーム: Dressing Pafé
  口癖: ドロシーがそう言うなら