lala:
  name: 真中らぁら
  cv: 茜屋日海夏
  grade: 小学5年生
  team: SoLaMi SMILE
  fav_phrase: かしこま！

mirei:
  name: 南みれぃ
  cv: 芹澤優
  grade: 中学1年生
  team: SoLaMi SMILE
  fav_phrase: 計算どおり

sophie:
  name: 北条そふぃ
  cv: 久保田未夢
  grade: 中学2年生
  team: SoLaMi SMILE
  fav_phrase: ぷしゅー

shion:
  name: 東堂シオン
  cv: 山北早紀
  grade: 中学1年生
  team: Dressing Pafé
  fav_phrase: いご

dorothy:
  name: ドロシー・ウェスト
  cv: 澁谷梓希
  grade: 中学1年生
  team: Dressing Pafé
  fav_phrase: テンションマックス

leona:
  name: レオナ・ウェスト
  cv: 若井友希
  grade: 中学1年生
  team: Dressing Pafé
  fav_phrase: ドロシーがそう言うなら
