1:
  title: アイドル始めちゃいました！
2:
  title: 約束やぶっちゃダメぷりっ
3:
  title: チーム解散？困るクマ～！
4:
  title: かしこま！元気 For You
5:
  title: あたし、そふぃさんと歌いたいワニ！
6:
  title: 異議あり？らぁらがウチにやってきたっぷり！
7:
  title: レッドフラッシュを探して…
8:
  title: ドキドキ！夏だ！水着だ！プールでかしこまっ♪
9:
  title: ときめきアイドル大集合！
10:
  title: 秋色ラブリーライブ
11:
  title: どうする？どうなる!?3人目!!!
12:
  title: はばたけ、そふぃ！
13:
  title: 空見て笑って♡チーム名発表！
14:
  title: ライバル登場！イゴ、よろしく!!
15:
  title: 一触即発？シオンVSみれぃぷりっ！
16:
  title: 特ダネ！らぁらのヒミツばれちゃった!?
17:
  title: 恐怖のハロウィン！ジャック・OH!蘭たん!?
18:
  title: レオナ、全力ダッシュなの！
19:
  title: みれぃとクマ、運命の出会いぷりクマ！
20:
  title: パスタVS忍者！
21:
  title: 解散!?そふぃ様親衛隊
22:
  title: 学園祭でライブクマ～！
23:
  title: 最後の日でっすわ！
24:
  title: さよなら、プリパラ
25:
  title: クリスマスプレゼントフォーユー！
26:
  title: いよいよあの子がデビューでちゅ
27:
  title: あけおめでかしこま！
28:
  title: プリパラ囲碁パンダでございます
29:
  title: EZ DO グロササイズ
30:
  title: ドキドキ！パラダイスコーデは誰のもの!?
31:
  title: スマイル！そらみ♡スマイル

